### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by sungjaecho97** [karlin13/yourssu-kwaje#1]

**Comment by karlin13** [comment]
No issue!
No issue in this proj yay!

**Comment by sungjaecho97** [comment]
Do you remember ACMICPC?
Hi How are you Find thank you and you?

**Comment by karlin13** [comment]
ryu jin no ken o kurae~~!!!
genji is with you (0 0)b

**Comment by sungjaecho97** [comment]
I don't think overwatch is a good idea to post on GITHUB. It is sacred... Yes Sacred.... Coding Sacred... Hmmm....Yum.......Yum...
And I DON'T PLAY OVERWATCH.

**Comment by karlin13** [comment]
I am almost JOT Mang shit
Mulli bigiseo a jik do da mot sut a yo

**Comment by sungjaecho97** [comment]
kkkkkkkkkkkk

**Comment by sungjaecho97** [comment]
maybe .. fedora is good...
Fe Fe Fedododo ra
